-- ============================================================
--  WordQuiz Database Schema
--  Oracle 11g compatible (SEQUENCE + TRIGGER)
--  Nhóm 3: 한덕인 · 부이휘황 · 바야르
-- ============================================================
 
-- ------------------------------------------------------------
--  BƯỚC 1: XOÁ BẢNG CŨ (bỏ qua nếu chưa có) 기존 테이블 삭제 (없으면 건너뜀)
-- ------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LEADERBOARD  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE QUIZ_SESSION CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WORDS        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES   CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USERS        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
 
-- ------------------------------------------------------------
--  BƯỚC 2: XOÁ SEQUENCE CŨ 기존 시퀀스 삭제 (없으면 건너뜀)
-- ------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USERS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CATEGORIES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_WORDS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SESSION';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RANK';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
 
-- ------------------------------------------------------------
--  BƯỚC 3: TẠO SEQUENCE 시퀀스 생성
-- ------------------------------------------------------------
CREATE SEQUENCE SEQ_USERS      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORIES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_WORDS      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SESSION    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RANK       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
 
-- ------------------------------------------------------------
--  BƯỚC 4: TẠO BẢNG 테이블 생성
-- ------------------------------------------------------------
CREATE TABLE USERS (
    USER_ID    NUMBER PRIMARY KEY,
    USERNAME   VARCHAR2(50)  NOT NULL UNIQUE,
    EMAIL      VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD   VARCHAR2(255) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);
 
CREATE TABLE CATEGORIES (
    CAT_ID   NUMBER PRIMARY KEY,
    CAT_NAME VARCHAR2(50) NOT NULL UNIQUE
);
 
CREATE TABLE WORDS (
    WORD_ID    NUMBER PRIMARY KEY,
    WORD_EN    VARCHAR2(100) NOT NULL,
    WORD_KO    VARCHAR2(100) NOT NULL,
    CAT_ID     NUMBER NOT NULL,
    DIFFICULTY NUMBER(1) NOT NULL CHECK (DIFFICULTY IN (1, 2, 3)),
    CONSTRAINT FK_WORDS_CAT FOREIGN KEY (CAT_ID) REFERENCES CATEGORIES(CAT_ID)
);
 
CREATE TABLE QUIZ_SESSION (
    SESSION_ID  NUMBER PRIMARY KEY,
    USER_ID     NUMBER NOT NULL,
    STARTED_AT  DATE DEFAULT SYSDATE,
    TOTAL_SCORE NUMBER DEFAULT 0,
    CONSTRAINT FK_SESSION_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
 
CREATE TABLE LEADERBOARD (
    RANK_ID     NUMBER PRIMARY KEY,
    USER_ID     NUMBER NOT NULL UNIQUE,
    TOTAL_SCORE NUMBER DEFAULT 0,
    UPDATED_AT  DATE DEFAULT SYSDATE,
    CONSTRAINT FK_RANK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
 
-- ------------------------------------------------------------
--  BƯỚC 5: TẠO TRIGGER 트리거 생성
-- ------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_USERS
BEFORE INSERT ON USERS FOR EACH ROW
BEGIN SELECT SEQ_USERS.NEXTVAL INTO :NEW.USER_ID FROM DUAL; END;
/
 
CREATE OR REPLACE TRIGGER TRG_CATEGORIES
BEFORE INSERT ON CATEGORIES FOR EACH ROW
BEGIN SELECT SEQ_CATEGORIES.NEXTVAL INTO :NEW.CAT_ID FROM DUAL; END;
/
 
CREATE OR REPLACE TRIGGER TRG_WORDS
BEFORE INSERT ON WORDS FOR EACH ROW
BEGIN SELECT SEQ_WORDS.NEXTVAL INTO :NEW.WORD_ID FROM DUAL; END;
/
 
CREATE OR REPLACE TRIGGER TRG_SESSION
BEFORE INSERT ON QUIZ_SESSION FOR EACH ROW
BEGIN SELECT SEQ_SESSION.NEXTVAL INTO :NEW.SESSION_ID FROM DUAL; END;
/
 
CREATE OR REPLACE TRIGGER TRG_RANK
BEFORE INSERT ON LEADERBOARD FOR EACH ROW
BEGIN SELECT SEQ_RANK.NEXTVAL INTO :NEW.RANK_ID FROM DUAL; END;
/
 
-- ------------------------------------------------------------
--  BƯỚC 6: TẠO INDEX 인덱스 생성
-- ------------------------------------------------------------
CREATE INDEX IDX_WORDS_DIFFICULTY ON WORDS(DIFFICULTY);
CREATE INDEX IDX_WORDS_CAT        ON WORDS(CAT_ID);
CREATE INDEX IDX_SESSION_USER     ON QUIZ_SESSION(USER_ID);
CREATE INDEX IDX_RANK_SCORE       ON LEADERBOARD(TOTAL_SCORE DESC);
 
-- ------------------------------------------------------------
--  BƯỚC 7: NHẬP CATEGORIES (19개) 카테고리 데이터 입력
-- ------------------------------------------------------------
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('동물');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('음식');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('동사');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('형용사');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('일상');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('자연');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('스포츠');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('직업');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('감정');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('기술');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('교육');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('의료');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('여행');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('경제');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('예술');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('환경');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('사회');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('색상');
INSERT INTO CATEGORIES (CAT_NAME) VALUES ('수학');
COMMIT;
 
-- ------------------------------------------------------------
--  KIỂM TRA 확인
-- ------------------------------------------------------------
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;
 
SELECT 'CATEGORIES'   AS TBL, COUNT(*) AS CNT FROM CATEGORIES
UNION ALL SELECT 'WORDS',        COUNT(*) FROM WORDS
UNION ALL SELECT 'USERS',        COUNT(*) FROM USERS
UNION ALL SELECT 'QUIZ_SESSION', COUNT(*) FROM QUIZ_SESSION
UNION ALL SELECT 'LEADERBOARD',  COUNT(*) FROM LEADERBOARD;
 
SELECT SEQUENCE_NAME FROM USER_SEQUENCES ORDER BY SEQUENCE_NAME;